name: MultiInventoryManager
author: RussianMushroom
main: io.github.russianmushroom.MultiInventoryManager
version: 0.8.0
description: Separates players' inventories among worlds.

commands:
  mim:
    description: MultiInventoryManager commands.
    usage: |
           /mim delete [player name]

permissions:
    mim.delete:
        description: deletes user's data file
        default: op
        command: "/mim delete"