name: MultiInventoryManager
author: RussianMushroom
main: io.github.russianmushroom.MultiInventoryManager
version: 0.9.0
description: Separates players' inventories among worlds.

commands:
  mim:
    description: MultiInventoryManager commands.

permissions:
    mim.delete:
        description: deletes user's data file
        default: op
        command: "/mim delete"